ALTER TABLE leads ADD COLUMN event_date  TEXT DEFAULT '';
ALTER TABLE leads ADD COLUMN venue       TEXT DEFAULT '';
ALTER TABLE leads ADD COLUMN schedule    TEXT DEFAULT '';
ALTER TABLE leads ADD COLUMN service     TEXT DEFAULT '';
ALTER TABLE leads ADD COLUMN last_msg_at INTEGER DEFAULT 0;
ALTER TABLE leads ADD COLUMN followup_due INTEGER DEFAULT 0;
